apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Use Helm chart inflator via kustomize
helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: "16.4.5"
    releaseName: poc-postgres
    namespace: poc-cfg-base
    includeCRDs: false
    valuesFile: values-postgres.yaml

resources:
  - demo-app-deployment.yaml
  - demo-app-configmap.yaml
  - demo-app-service.yaml
  - external-secret.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: poc-config-mgmt
      managed-by: argocd
