apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: poc-cfg-prod

resources:
  - ../../base
  - backup-cronjob.yaml  # Only in prod

labels:
  - pairs:
      environment: production

patches:
  # Update ConfigMap for prod environment
  - target:
      kind: ConfigMap
      name: poc-demo-app-config
    patch: |-
      - op: replace
        path: /data/PUBLIC_URL
        value: "https://prod.example.local"
      - op: replace
        path: /data/ENVIRONMENT
        value: "production"
  
  # Use stable image tag for prod with more replicas
  - target:
      kind: Deployment
      name: poc-demo-app
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: "nginx:1.24-alpine"
      - op: replace
        path: /spec/replicas
        value: 2

  # Update PostgreSQL storage for prod
  - target:
      kind: StatefulSet
      name: poc-postgres-postgresql
    patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: "gp2"
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: "5Gi"
