apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postgres.yaml
- postgres-backup-pvc.yaml
- postgres-backup-cronjob.yaml

labels:
- pairs:
    app: lhw-openproject
    managed-by: argocd